name: cross-platform-release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/build-linux.yml

  windows:
    uses: ./.github/workflows/build-windows.yml

  android:
    uses: ./.github/workflows/build-android.yml

  release:
    needs: [linux, windows, android]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
